server:
  port: 8080 # Порт для API Gateway

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081 # URL вашого UserService
          predicates:
            - Path=/users/** # Маршрутизація всіх запитів із префіксом /users
        - id: course-service
          uri: http://localhost:8082
          predicates:
            - Path=/courses/**
        - id: certification-service
          uri: http://localhost:8083
          predicates:
            - Path=/certifications/**
        - id: progresstrack-service
          uri: http://localhost:8084
          predicates:
            - Path=/progress/**        
        - id: notification-service
          uri: http://localhost:8085
          predicates:
            - Path=/notification/**